version: '3.8'

services:
  web:
    container_name: merch-shop-service
    build: .
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/shop
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static_volume:/app/static
    networks:
      - internal

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
     - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'sh -c "pg_isready -U user -d shop"']
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal

networks:
  internal:
  
volumes:
  pg_data:
  static_volume:
    